import { useEffect, useState } from 'react';
import { CloseIcon, PrinterIcon } from './icons';
import Badge, { type BadgeTone } from './Badge';
import { formatCurrency } from '../lib/format';
import { cachedGet } from '../lib/queryCache';
import type { ReceiptData } from '../lib/receipt';

interface ReceiptModalProps {
  data: ReceiptData | null;
  onClose: () => void;
}

const statusTone = (status: string): BadgeTone => {
  if (status === 'paid') return 'success';
  if (status === 'partial') return 'warning';
  return 'danger';
};

const ReceiptModal = ({ data, onClose }: ReceiptModalProps) => {
  const [portfolioName, setPortfolioName] = useState('');

  useEffect(() => {
    if (!data) return;
    let active = true;
    cachedGet('/portfolio')
      .then((res) => {
        if (active) setPortfolioName(res?.portfolio?.name || '');
      })
      .catch(() => {});
    return () => {
      active = false;
    };
  }, [data]);

  if (!data) return null;

  return (
    <div className="receipt-modal-backdrop fixed inset-0 z-[130] flex items-center justify-center bg-slate-950/40 p-6 backdrop-blur-sm">
      <div className="receipt-modal-shell w-full max-w-lg rounded-3xl border border-black/5 bg-white shadow-2xl">
        <div className="receipt-modal-toolbar flex items-center justify-between border-b border-black/5 px-6 py-4">
          <div className="text-sm font-semibold text-[var(--muted)]">Receipt Preview</div>
          <div className="flex items-center gap-2">
            <button
              type="button"
              className="btn btn-sm btn-info"
              onClick={() => window.print()}
            >
              <PrinterIcon width={14} height={14} />
              Print / Save PDF
            </button>
            <button type="button" className="modal-close-btn" onClick={onClose} aria-label="Close">
              <CloseIcon width={18} height={18} />
            </button>
          </div>
        </div>

        <div className="receipt-print-area px-8 py-8">
          {portfolioName && (
            <div className="mb-4 border-b border-black/10 pb-3 text-center">
              <div className="text-base font-bold tracking-tight text-[var(--accent)]">{portfolioName}</div>
              <div className="text-[10px] uppercase tracking-[0.2em] text-[var(--muted)]">Property Management</div>
            </div>
          )}
          <div className="flex items-start justify-between gap-4 border-b border-dashed border-black/10 pb-4">
            <div>
              <div className="text-lg font-bold tracking-tight">{data.propertyName}</div>
              {data.propertyAddress && <div className="mt-0.5 text-xs text-[var(--muted)]">{data.propertyAddress}</div>}
            </div>
            <div className="text-right">
              <div className="text-sm font-semibold text-[var(--accent)]">{data.title}</div>
              <div className="mt-0.5 text-xs text-[var(--muted)]">Receipt No. {data.receiptNo}</div>
              {data.date && <div className="text-xs text-[var(--muted)]">{data.date}</div>}
            </div>
          </div>

          {(data.tenantName || data.unitNumber) && (
            <div className="mt-4 flex flex-wrap items-center gap-2 text-sm">
              {data.tenantName && <span className="font-medium">{data.tenantName}</span>}
              {data.unitNumber && (
                <Badge tone="info" dot={false} className="!px-2.5 !py-0.5 !text-xs !font-medium">
                  Unit {data.unitNumber}
                </Badge>
              )}
              {data.status && (
                <Badge tone={statusTone(data.status)} dot={false} className="!px-2.5 !py-0.5 !text-xs !font-medium capitalize">
                  {data.status}
                </Badge>
              )}
            </div>
          )}

          <div className="mt-5 space-y-2 rounded-2xl bg-[var(--surface-1)] p-4 text-sm">
            {data.items.map((item, index) => (
              <div key={index} className="flex items-center justify-between gap-4">
                <span className="text-[var(--muted)]">{item.label}</span>
                <span className="font-medium text-right">{item.value}</span>
              </div>
            ))}
          </div>

          <div className="mt-5 flex items-center justify-between rounded-2xl border border-[var(--accent)]/20 bg-[var(--accent-soft)] px-4 py-3.5">
            <span className="text-sm font-semibold text-[var(--text)]">{data.amountLabel}</span>
            <span className="text-2xl font-bold text-[var(--accent)]">₹{formatCurrency(data.amount)}</span>
          </div>

          {data.notes && <div className="mt-4 text-xs text-[var(--muted)]">{data.notes}</div>}

          <div className="mt-8 text-center text-[11px] text-[var(--muted)]">Generated by RentDesk · {new Date().toLocaleString('en-IN')}</div>
        </div>
      </div>

      <style>{`
        @media print {
          body * { visibility: hidden; }
          .receipt-print-area, .receipt-print-area * { visibility: visible; }
          .receipt-print-area {
            position: fixed;
            inset: 0;
            padding: 24px;
          }
          .receipt-modal-backdrop { background: transparent !important; backdrop-filter: none !important; position: static !important; }
          .receipt-modal-shell { box-shadow: none !important; border: none !important; max-width: 100% !important; }
          .receipt-modal-toolbar { display: none !important; }
        }
      `}</style>
    </div>
  );
};

export default ReceiptModal;
